name: 🚀 Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: castmanu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Modificar database.py con datos de producción
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sed -i "/^\s*host='localhost'/ s/host='localhost'/host=\"bbdd.castmanu.com\"/" app/database.py
          sed -i "/^\s*user='root'/ s/user='root'/user=\"ddb252198\"/" app/database.py
          sed -i "/^\s*password='calamatzoc'/ s/password='calamatzoc'/password=\"${DB_PASSWORD}\"/" app/database.py
          sed -i "/^\s*db='castmanu'/ s/db='castmanu'/db=\"ddb252198\"/" app/database.py

      - name: Install flyctl manually
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
      
      - name: Authenticate Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly tokens create $FLY_API_TOKEN

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd app
          fly deploy --remote-only